name: Build Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: robinj1995/meme-gen/meme-gen
        registry: ghcr.io
        username: RobinJ1995
        password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        snapshot: true
